# Generated by Django 2.2.4 on 2019-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='None', max_length=254, null=True),
        ),
    ]
