# Generated by Django 2.2.4 on 2019-08-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_login',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
