# Generated by Django 2.2.4 on 2019-08-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_token_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shift', models.CharField(max_length=20)),
            ],
        ),
    ]
