# Generated by Django 2.2.4 on 2019-08-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Shift'),
        ),
    ]
