# Generated by Django 2.2.4 on 2019-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_student_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name_shift',
            field=models.CharField(max_length=50),
        ),
    ]
