# Generated by Django 2.2.4 on 2019-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20190819_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(default='media/avatars/008-twitter.png', null=True, upload_to='media/avatars'),
        ),
    ]
