# Generated by Django 2.2.4 on 2019-08-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20190819_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(default='media/avatars/logo.jpg', null=True, upload_to='media/avatars'),
        ),
    ]
