# Generated by Django 2.2.4 on 2019-08-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190819_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Shift'),
        ),
    ]
