# Generated by Django 2.2.4 on 2019-08-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
