# Generated by Django 2.2.4 on 2019-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_student_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
