# Generated by Django 2.2.4 on 2019-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20190819_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
