# Generated by Django 2.2.4 on 2019-08-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_shift_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
