# Generated by Django 2.2.4 on 2019-08-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_prevshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prevShift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.PrevShift'),
        ),
    ]
