# Generated by Django 2.2.4 on 2019-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20190819_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='prevShift',
        ),
        migrations.AddField(
            model_name='student',
            name='is_been',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='prevShift',
        ),
    ]
